### ISSUE TITLE
Roadmap переводов книг

### ISSUE THREAD

**Issue by funkill** [ruRust/community#32]
- [ ] Async Book - #27
- [ ] The Rust Programming Language - #3 
- [ ] The Rustonomicon - #28 
- [ ] Too Many Linked Lists - #29 
- [ ] The Little Book of Rust Macros - #31 
- [ ] Cargo doc - #30
